# Generated by Django 4.1.7 on 2023-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="title of job"),
                ),
                ("description", models.TextField(verbose_name="description of job")),
                (
                    "company",
                    models.CharField(
                        max_length=200, verbose_name="name of company posting job"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=300, verbose_name="location of job"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=200, verbose_name="contact for company"
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        max_length=60, verbose_name="website of the company"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        upload_to="logo", verbose_name="logo of the company"
                    ),
                ),
            ],
        ),
    ]
