# Generated by Django 4.1.7 on 2023-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="logo",
            field=models.ImageField(
                null=True, upload_to="logo", verbose_name="logo of the company"
            ),
        ),
    ]
