# Generated by Django 4.1.7 on 2023-02-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postings", "0002_alter_posting_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="company",
            field=models.CharField(
                help_text="name of company posting job", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="posting",
            name="description",
            field=models.TextField(help_text="description of job"),
        ),
        migrations.AlterField(
            model_name="posting",
            name="email",
            field=models.EmailField(help_text="contact for company", max_length=200),
        ),
        migrations.AlterField(
            model_name="posting",
            name="location",
            field=models.CharField(help_text="location of job", max_length=300),
        ),
        migrations.AlterField(
            model_name="posting",
            name="logo",
            field=models.ImageField(
                blank=True, help_text="logo of the company", null=True, upload_to="logo"
            ),
        ),
        migrations.AlterField(
            model_name="posting",
            name="title",
            field=models.CharField(help_text="title of job", max_length=200),
        ),
        migrations.AlterField(
            model_name="posting",
            name="website",
            field=models.CharField(help_text="website of the company", max_length=60),
        ),
    ]
