# Generated by Django 4.1.7 on 2023-03-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postings", "0003_alter_posting_company_alter_posting_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="posting",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="logo of the company",
                null=True,
                upload_to="logo/",
            ),
        ),
        migrations.AddField(
            model_name="posting",
            name="tags",
            field=models.ManyToManyField(to="postings.tag"),
        ),
    ]
