# Generated by Django 4.1.7 on 2023-03-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postings", "0005_tag_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
