# Generated by Django 4.1.7 on 2024-12-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postings", "0007_posting_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posting",
            name="tags",
        ),
        migrations.AddField(
            model_name="posting",
            name="tags",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
