# Generated by Django 4.1.7 on 2024-12-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postings", "0008_remove_posting_tags_posting_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="tags",
            field=models.CharField(max_length=100),
        ),
    ]
