# Generated by Django 4.1.7 on 2023-02-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateTimeField(null=True, verbose_name="date of birth"),
        ),
    ]
