# Generated by Django 4.1.7 on 2023-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="designates whether user can access admin page",
                verbose_name="staff status",
            ),
        ),
    ]
